version: '3.1'

services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - 5672:5672
      - 15671:15671
      - 15672:15672
    networks:
      - messaging
  elastic-search:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.1
    restart: always
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
    volumes:
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ${ES_VOLUME}:/usr/share/elasticsearch/data
    ports:
      - 9300:9300
      - 9200:9200
  database:
    image: postgres:11
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ${POSTGRES_VOLUME}:/var/lib/postgresql/data
    networks:
      - database

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - "${MONGO_VOLUME}:/var/lib/mongodb"

  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
    networks:
      - in_memory_storage

networks:
  database:
    driver: bridge
  messaging:
    driver: bridge
  in_memory_storage:
    driver: bridge